Resources:
  PUBLICVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: VPC_DEV

Outputs:
  VpcId:
    Description: The VPC 
    Value: !Ref PUBLICVPC

